package pt.isel.mpd.v1718.li42d;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import pt.isel.mpd.v1718.li42d.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();

        assertEquals("SLB", classUnderTest.getGreeting());
    }

    @Test
    public void test1() {

    }

    @Test
    public void test2() {

    }
}
