package pt.isel.mpd.v1718.li42d;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import pt.isel.mpd.v1718.li42d.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
